language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
install: "pip install python-daemon"
script: "python -m unittest -v tests.test_command tests.test_config tests.test_core tests.test_database tests.test_formatters tests.test_login tests.test_session tests.test_shell"
